name: Publish release

description: Infers current project version, pushes a tag with a new version, and creates an entry on GitHub Releases


inputs:
  new-version:
    description: Optional override for the release version. If not provided, will be inferred from current version.
    required: false


outputs:
  release-version:
    description: Version that the release ended up running for.
    value: ${{ steps.infer-release-version.outputs.inferred_version }}

runs:
  using: composite
  steps:
    # ATM the "uses" keyword is unsupported for steps nested in a composite action.
    # - name: Check out the released repo
    #   uses: actions/checkout@v2
    #   with:
    #     # Fetch whole repo to get access to tags. We need tags to read current package
    #     # version.
    #     fetch-depth: 0
    - name: Run git clone     
      shell: bash
      run: |
        git clone https://${{ github.token }}@github.com/${{ github.token }}.git


    - name: Infer release version
      id: infer-release-version
      shell: bash
      run: |
        NEW_VERSION="${{ inputs.new_version }}"
        if [ -n "$NEW_VERSION" ]; then
          INFERRED_VERSION="$NEW_VERSION"
          echo "using $INFERRED_VERSION provided as action input"
        else
          PKG_VERSION=$(python3 setup.py --version)

          MAJOR=$(echo $PKG_VERSION | sed -r 's/^([0-9]+)\.([0-9]+)\.([0-9]+)([-\.].+)?$/\1/')
          MINOR=$(echo $PKG_VERSION | sed -r 's/^([0-9]+)\.([0-9]+)\.([0-9]+)([-\.].+)?$/\2/')
          PATCH=$(echo $PKG_VERSION | sed -r 's/^([0-9]+)\.([0-9]+)\.([0-9]+)([-\.].+)?$/\3/')
          DEV=$(echo $PKG_VERSION | sed -r 's/^([0-9]+)\.([0-9]+)\.([0-9]+)([-\.].+)?$/\4/')
          echo "read version: $MAJOR.$MINOR.$PATCH$DEV"

          INFERRED_VERSION="$MAJOR.$(expr $MINOR + 1).0"
          echo "inferred version: $INFERRED_VERSION"
        fi
        # special github syntax for setting step outputs
        # see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter
        echo "::set-output name=inferred_version::$INFERRED_VERSION"

    - name: Push new version tag
      shell: bash
      run: |
        TAG="v${{steps.infer-release-version.outputs.inferred_version}}"
        git tag "$TAG"
        git push --tags
